### PR TITLE
Make C pacextractor compatible with 32-bit systems when dealing with > 2GB files

### PR DESCRIPTION
**Pull request by kyufie**
If C pacextractor is compiled for 32-bit system, things will start to get messy when dealing with huge files (due to the limitation in 32-bit system).
This will fix it.

### CODE REVIEW

**Comment by HemanthJabalpuri** [comment]
What about Python and Java codes?

**Comment by kyufie** [comment]
I don't know about Java, but Python generally has support for large files.
I only provide changes to the C code to make it more compatible with 32-bit system.

**Comment by HemanthJabalpuri** [comment]
Thanks for contribution, let me know any other changes needed. I know that my C code is not properly placed and not easily understandable :(

**Comment by kyufie** [comment]
You're welcome.

**Pull request merged**
